server:
  port: 9998
  servlet:
    context-path: /cloud-agent
spring:
  application:
    name: cloud-agent
#日志文件输出路径
logging:
  file:
    path: ./log

#自定义配置参数
base:
  #cloud-server端访问地址
  serverUrl: http://localhost:9999
  #本机ip
  bindIp: FuzerdR7000
  #通信token，请和server端配置的wgToken保持一致
  wgToken: Fuzerd